export const allProducts =[
  {
    id: 1,
    name: "FocusFlow",
    slug: "focus-flow",
    tagline: "Bloqueador de distracciones inteligente basado en biometría.",
    description: "Una aplicación de escritorio que utiliza la cámara para detectar signos de fatiga y falta de concentración, ajustando automáticamente tu entorno de trabajo y bloqueando notificaciones irrelevantes.",
    websiteUrl: "https://focusflow.io",
    tags: ["Productividad", "IA", "Bienestar"],
    votecount: 1250,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    status: "APPROVED",
    submittedBy: "user_88"
  },
  {
    id: 2,
    name: "CodeMentor AI",
    slug: "codementor-ai",
    tagline: "Revisiones de código en tiempo real con explicaciones pedagógicas.",
    description: "No es solo un linter; es un tutor que analiza tus Pull Requests y te explica el 'por qué' detrás de cada sugerencia de optimización de código.",
    websiteUrl: "https://codementor.ai",
    tags: ["Desarrollo", "Educación", "IA"],
    votecount: 890,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    status: "APPROVED",
    submittedBy: "dev_master"
  },
  {
    id: 3,
    name: "GreenTrack",
    slug: "greentrack",
    tagline: "Calcula y compensa tu huella de carbono digital.",
    description: "Extensión de navegador que mide el consumo energético de los sitios que visitas y te sugiere alternativas más sostenibles.",
    websiteUrl: "https://greentrack.org",
    tags: ["Ecología", "Navegación", "Herramientas"],
    votecount: 450,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    status: "APPROVED",
    submittedBy: "eco_warrior"
  },
  {
    id: 4,
    name: "SoundScape Pro",
    slug: "soundscape-pro",
    tagline: "Generador de ambientes sonoros dinámicos para RPGs.",
    description: "Plataforma para Game Masters que genera música y efectos de sonido procedimentales que reaccionan a las decisiones de los jugadores en tiempo real.",
    websiteUrl: "https://soundscape.pro",
    tags: ["Gaming", "Música", "Audio"],
    votecount: 2100,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    status: "APPROVED",
    submittedBy: "rpg_king"
  },
  {
    id: 5,
    name: "MindUI",
    slug: "mind-ui",
    tagline: "Diseña interfaces de usuario usando solo comandos de voz.",
    description: "Herramienta de diseño 'hands-free' que permite a diseñadores con discapacidades motoras crear prototipos de alta fidelidad en Figma mediante lenguaje natural.",
    websiteUrl: "https://mindui.design",
    tags: ["Diseño", "Accesibilidad", "IA"],
    votecount: 3400,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    status: "APPROVED",
    submittedBy: "design_forall"
  },
  {
    id: 6,
    name: "RecipeBot",
    slug: "recipe-bot",
    tagline: "Crea recetas basadas en lo que tienes en tu refrigerador.",
    description: "Escanea tus ingredientes con la cámara del móvil y obtén recetas personalizadas para evitar el desperdicio de comida.",
    websiteUrl: "https://recipebot.app",
    tags: ["Lifestyle", "Cocina", "IA"],
    votecount: 670,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    status: "APPROVED",
    submittedBy: "chef_digital"
  },
  {
    id: 7,
    name: "CryptoGuard",
    slug: "cryptoguard",
    tagline: "Auditoría de seguridad instantánea para Smart Contracts.",
    description: "Una herramienta CLI que analiza vulnerabilidades comunes en contratos Solidity antes de desplegarlos en la mainnet.",
    websiteUrl: "https://cryptoguard.io",
    tags: ["Blockchain", "Seguridad", "Web3"],
    votecount: 520,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    status: "APPROVED",
    submittedBy: "eth_coder"
  },
  {
    id: 8,
    name: "LearnLinguist",
    slug: "learn-linguist",
    tagline: "Intercambio de idiomas en mundos de realidad virtual.",
    description: "Sumergete en ciudades virtuales donde debes hablar el idioma local para interactuar con NPCs y otros usuarios para completar misiones.",
    websiteUrl: "https://learnlinguist.vr",
    tags: ["Educación", "VR", "Idiomas"],
    votecount: 150,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    status: "PENDING",
    submittedBy: "polyglot_99"
  },
  {
    id: 9,
    name: "DataViz Wizard",
    slug: "dataviz-wizard",
    tagline: "Convierte archivos CSV aburridos en infografías animadas.",
    description: "Sube tus datos y deja que la IA elija la mejor narrativa visual para presentar tus métricas en reuniones de alto nivel.",
    websiteUrl: "https://dataviz.wizard",
    tags: ["Data", "Marketing", "SaaS"],
    votecount: 980,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    status: "APPROVED",
    submittedBy: "analyst_pro"
  },
  {
    id: 10,
    name: "FitSync",
    slug: "fitsync",
    tagline: "Entrenador personal que ajusta tu rutina según tu calidad de sueño.",
    description: "Sincroniza tus datos de sueño de cualquier wearable y FitSync rediseña tu entrenamiento del día para maximizar ganancias o evitar el sobreentrenamiento.",
    websiteUrl: "https://fitsync.app",
    tags: ["Salud", "Fitness", "Wearables"],
    votecount: 1120,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    status: "APPROVED",
   "submittedB": "fitness_freak"
  }
];